const DB_NAME='yonkomaStockDB',STORE='items',SUPABASE_BUCKET='yonkoma-stock',SUPABASE_TABLE='yonkoma_items',CONFIG_KEY='yonkomaStockSupabaseConfig';
let db,currentFilter='all',editingId=null,previewUrl=null,sb=null,currentUser=null,syncRunning=false,syncTimer=null;
const $=s=>document.querySelector(s),nowIso=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID(),fmt=i=>new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(i));
const statusLabel={idea:'ネタ',making:'制作中',ready:'完成・未使用',used:'使用済み'},nextStatus={idea:'making',making:'ready',ready:'used',used:'ready'},nextLabel={idea:'制作中へ',making:'完成にする',ready:'使用済みにする',used:'未使用に戻す'};
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2200)}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE)){const s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('createdAt','createdAt');s.createIndex('status','status')}};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
const store=(m='readonly')=>db.transaction(STORE,m).objectStore(STORE);function allRaw(){return new Promise((r,j)=>{const q=store().getAll();q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}async function all(){return (await allRaw()).filter(x=>!x.deleted)}function get(id){return new Promise((r,j)=>{const q=store().get(id);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}function put(x){return new Promise((r,j)=>{const q=store('readwrite').put(x);q.onsuccess=()=>r();q.onerror=()=>j(q.error)})}
async function render(){let items=await all();for(const k of ['idea','making','ready','used'])$('#'+k+'Count').textContent=items.filter(x=>x.status===k).length;$('#totalCount').textContent=items.length;let shown=currentFilter==='all'?items:items.filter(x=>x.status===currentFilter);const sort=$('#sortSelect').value,order={idea:0,making:1,ready:2,used:3};shown.sort((a,b)=>sort==='oldest'?new Date(a.createdAt)-new Date(b.createdAt):sort==='status'?(order[a.status]-order[b.status]||new Date(b.createdAt)-new Date(a.createdAt)):new Date(b.createdAt)-new Date(a.createdAt));$('#emptyState').classList.toggle('hidden',items.length>0);const grid=$('#grid');grid.innerHTML='';for(const item of shown){const n=$('#cardTemplate').content.cloneNode(true),card=n.querySelector('.card');card.dataset.status=item.status;n.querySelector('.status-badge').textContent=statusLabel[item.status];n.querySelector('.card-title').textContent=item.title||'無題の4コマ';n.querySelector('.created-at').textContent=fmt(item.createdAt);n.querySelector('.theme').textContent=item.theme||'';const p=n.querySelector('.post-text');p.textContent=item.postText||item.memo||'';p.classList.toggle('hidden',!p.textContent);if(item.imageBlob){const u=URL.createObjectURL(item.imageBlob),img=n.querySelector('.thumb');img.src=u;img.classList.remove('hidden');n.querySelector('.no-image').classList.add('hidden');img.onload=()=>setTimeout(()=>URL.revokeObjectURL(u),1000)}n.querySelector('.image-wrap').onclick=()=>openEditor(item.id);n.querySelector('.edit-btn').onclick=()=>openEditor(item.id);n.querySelector('.copy-btn').onclick=()=>copyPost(item);n.querySelector('.next-btn').textContent=nextLabel[item.status];n.querySelector('.next-btn').onclick=()=>advance(item.id);grid.appendChild(n)}}
function setFilter(f){currentFilter=f;document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.filter===f));render()}
async function copyPost(item){if(!item.postText){toast('投稿文がありません');return}try{await navigator.clipboard.writeText(item.postText);toast('投稿文をコピーしました')}catch{toast('コピーできませんでした')}}
async function advance(id){const x=await get(id);x.status=nextStatus[x.status];x.usedAt=x.status==='used'?nowIso():null;x.updatedAt=nowIso();await put(x);await render();scheduleSync()}
function resetEditor(){editingId=null;$('#dialogTitle').textContent='4コマを追加';$('#titleInput').value='';$('#postInput').value='';$('#memoInput').value='';$('#themeInput').value='';$('#statusInput').value='idea';$('#imageInput').value='';$('#dialogPreview').classList.add('hidden');$('#dialogPreview').removeAttribute('src');$('#dialogMeta').textContent='';$('#deleteBtn').classList.add('hidden')}
async function openEditor(id=null){resetEditor();if(id){const x=await get(id);editingId=id;$('#dialogTitle').textContent='4コマを編集';$('#titleInput').value=x.title||'';$('#postInput').value=x.postText||'';$('#memoInput').value=x.memo||'';$('#themeInput').value=x.theme||'';$('#statusInput').value=x.status||'idea';$('#dialogMeta').textContent=`登録：${fmt(x.createdAt)}${x.usedAt?' / 使用：'+fmt(x.usedAt):''}`;$('#deleteBtn').classList.remove('hidden');if(x.imageBlob){previewUrl=URL.createObjectURL(x.imageBlob);$('#dialogPreview').src=previewUrl;$('#dialogPreview').classList.remove('hidden')}}$('#editDialog').showModal()}
$('#imageInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(f);$('#dialogPreview').src=previewUrl;$('#dialogPreview').classList.remove('hidden')};
async function saveEditor(){const old=editingId?await get(editingId):null,file=$('#imageInput').files[0],status=$('#statusInput').value;const x={id:old?.id||uuid(),title:$('#titleInput').value.trim(),postText:$('#postInput').value.trim(),memo:$('#memoInput').value.trim(),theme:$('#themeInput').value.trim(),status,imageBlob:file||old?.imageBlob||null,imageName:file?.name||old?.imageName||'',imageType:file?.type||old?.imageType||'image/png',storagePath:old?.storagePath||'',createdAt:old?.createdAt||nowIso(),usedAt:status==='used'?(old?.usedAt||nowIso()):null,updatedAt:nowIso(),deleted:false};if(!x.title&&!x.postText&&!x.memo&&!x.imageBlob){toast('タイトル・投稿文・メモ・画像のどれかを入力してください');return}await put(x);$('#editDialog').close();await render();toast(editingId?'更新しました':'追加しました');scheduleSync()}
async function removeEditing(){if(!editingId||!confirm('この4コマを削除しますか？'))return;const x=await get(editingId);x.deleted=true;x.updatedAt=nowIso();await put(x);$('#editDialog').close();await render();toast('削除しました');scheduleSync()}
async function backup(){const items=await allRaw(),data=[];for(const x of items){const y={...x,imageBlob:null,imageData:null};if(x.imageBlob)y.imageData=await blobToData(x.imageBlob);data.push(y)}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,items:data},null,2)],{type:'application/json'}));a.download=`4koma-stock-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
const blobToData=b=>new Promise(r=>{const f=new FileReader();f.onload=()=>r(f.result);f.readAsDataURL(b)});async function dataToBlob(d){return fetch(d).then(r=>r.blob())}
async function restore(file){try{const j=JSON.parse(await file.text());for(const y of j.items||[]){if(y.imageData)y.imageBlob=await dataToBlob(y.imageData);delete y.imageData;y.updatedAt=nowIso();await put(y)}await render();toast('復元しました');scheduleSync()}catch{toast('復元できませんでした')}}
function config(){try{return JSON.parse(localStorage.getItem(CONFIG_KEY)||'null')}catch{return null}}function initSupabase(){const c=config();if(!c||!window.supabase)return false;sb=window.supabase.createClient(c.url,c.key);return true}function updateSyncUI(s){const el=$('#syncStatus'),m={local:'ローカルのみ',signedout:'同期：未ログイン',syncing:'同期中…',ok:'同期済み',error:'同期エラー',offline:'オフライン'};el.dataset.state=s;el.textContent=m[s]||m.local}async function session(){if(!sb)return;const {data}=await sb.auth.getSession();currentUser=data.session?.user||null;updateSyncUI(currentUser?'ok':'signedout')}
async function openSync(){const c=config();$('#supabaseUrl').value=c?.url||'';$('#supabaseKey').value=c?.key||'';$('#authPanel').classList.toggle('hidden',!c);$('#loggedInPanel').classList.toggle('hidden',!currentUser);$('#loggedOutPanel').classList.toggle('hidden',!!currentUser);$('#loggedInEmail').textContent=currentUser?.email||'';$('#syncDialog').showModal()}
async function saveCloud(){const url=$('#supabaseUrl').value.trim(),key=$('#supabaseKey').value.trim();if(!url||!key){toast('URLとキーを入力してください');return}localStorage.setItem(CONFIG_KEY,JSON.stringify({url,key}));initSupabase();await session();$('#authPanel').classList.remove('hidden');toast('設定を保存しました')}
async function signIn(){const {data,error}=await sb.auth.signInWithPassword({email:$('#syncEmail').value.trim(),password:$('#syncPassword').value});if(error){toast('ログインできませんでした');return}currentUser=data.user;$('#syncDialog').close();await syncNow();toast('ログインしました')}async function signUp(){const {data,error}=await sb.auth.signUp({email:$('#syncEmail').value.trim(),password:$('#syncPassword').value});if(error){toast(error.message);return}currentUser=data.session?.user||null;toast(currentUser?'アカウントを作成しました':'確認メールを開いて登録を完了してください');if(currentUser)await syncNow()}async function signOut(){await sb.auth.signOut();currentUser=null;updateSyncUI('signedout');toast('ログアウトしました')}
function scheduleSync(){clearTimeout(syncTimer);syncTimer=setTimeout(syncNow,500)}
async function syncNow(){if(syncRunning||!sb||!currentUser||!navigator.onLine)return;syncRunning=true;updateSyncUI('syncing');try{let local=await allRaw();const {data:remote,error}=await sb.from(SUPABASE_TABLE).select('*');if(error)throw error;const rm=new Map((remote||[]).map(r=>[r.id,r]));for(const x of local){const r=rm.get(x.id);if(!r||new Date(x.updatedAt)>new Date(r.updated_at)){let path=x.storagePath||r?.storage_path||'';if(x.imageBlob&&!x.deleted){path=path||`${currentUser.id}/${x.id}.${(x.imageType||'image/png').split('/')[1]||'png'}`;const up=await sb.storage.from(SUPABASE_BUCKET).upload(path,x.imageBlob,{upsert:true,contentType:x.imageType||'image/png'});if(up.error)throw up.error}const row={id:x.id,user_id:currentUser.id,title:x.title||'',post_text:x.postText||'',memo:x.memo||'',theme:x.theme||'',status:x.status||'idea',created_at:x.createdAt,used_at:x.usedAt||null,image_name:x.imageName||'',image_type:x.imageType||'image/png',storage_path:path,updated_at:x.updatedAt,deleted:!!x.deleted};const q=await sb.from(SUPABASE_TABLE).upsert(row);if(q.error)throw q.error;x.storagePath=path;await put(x)}}
const {data:fresh,error:fe}=await sb.from(SUPABASE_TABLE).select('*');if(fe)throw fe;local=await allRaw();const lm=new Map(local.map(x=>[x.id,x]));for(const r of fresh||[]){const l=lm.get(r.id);if(!l||new Date(r.updated_at)>new Date(l.updatedAt)){let blob=l?.imageBlob||null;if(r.storage_path&&!r.deleted){const dl=await sb.storage.from(SUPABASE_BUCKET).download(r.storage_path);if(!dl.error)blob=dl.data}await put({id:r.id,title:r.title,postText:r.post_text,memo:r.memo,theme:r.theme,status:r.status,imageBlob:blob,imageName:r.image_name,imageType:r.image_type,storagePath:r.storage_path,createdAt:r.created_at,usedAt:r.used_at,updatedAt:r.updated_at,deleted:r.deleted})}}await render();updateSyncUI('ok')}catch(e){console.error(e);updateSyncUI('error');toast('同期エラー：設定SQLを確認してください')}finally{syncRunning=false}}
$('#addBtn').onclick=()=>openEditor();$('#saveBtn').onclick=saveEditor;$('#deleteBtn').onclick=removeEditing;$('#backupBtn').onclick=backup;$('#restoreBtn').onclick=()=>$('#restoreInput').click();$('#restoreInput').onchange=e=>{if(e.target.files[0])restore(e.target.files[0]);e.target.value=''};$('.tabs').onclick=e=>{if(e.target.matches('.tab'))setFilter(e.target.dataset.filter)};document.querySelector('.summary').onclick=e=>{const b=e.target.closest('[data-filter]');if(b)setFilter(b.dataset.filter)};$('#sortSelect').onchange=render;$('#syncBtn').onclick=openSync;$('#saveCloudConfigBtn').onclick=saveCloud;$('#signInBtn').onclick=signIn;$('#signUpBtn').onclick=signUp;$('#signOutBtn').onclick=signOut;$('#syncNowBtn').onclick=syncNow;window.addEventListener('online',scheduleSync);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')scheduleSync()});
(async()=>{db=await openDB();await render();if(initSupabase()){await session();if(currentUser)scheduleSync();sb.auth.onAuthStateChange((_e,s)=>{currentUser=s?.user||null;if(currentUser)scheduleSync()})}if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{})})();
